### ISSUE TITLE
No search context found for id error

### ISSUE THREAD

**Issue by tiredpixel** [openownership/register-ingester-dk#17]
This month's bulk data import crashed during DK ingestion with _No search context found for id_.

I haven't investigated, but I suspect that something took too long, and the scroll cursor timed out.

I'm trying to simply rerun the entire DK ingestion.

```
/usr/local/bundle/gems/elasticsearch-transport-7.17.7/lib/elasticsearch/transport/transport/base.rb:218:in `__raise_transport_error': [404] {"error":{"root_cause":[{"type":"search_context_missing_exception","reason":"No search context found for id [325827711]"},{"type":"search_context_missing_exception","reason":"No search context found for id [325827713]"},{"type":"search_context_missing_exception","reason":"No search context found for id [325827712]"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":-1,"index":null,"reason":{"type":"search_context_missing_exception","reason":"No search context found for id [325827711]"}},{"shard":-1,"index":null,"reason":{"type":"search_context_missing_exception","reason":"No search context found for id [325827713]"}},{"shard":-1,"index":null,"reason":{"type":"search_context_missing_exception","reason":"No search context found for id [325827712]"}}],"caused_by":{"type":"search_context_missing_exception","reason":"No search context found for id [325827712]"}},"status":404} (Elasticsearch::Transport::Transport::Errors::NotFound)
        from /usr/local/bundle/gems/elasticsearch-transport-7.17.7/lib/elasticsearch/transport/transport/base.rb:341:in `perform_request'
        from /usr/local/bundle/gems/elasticsearch-transport-7.17.7/lib/elasticsearch/transport/transport/http/faraday.rb:36:in `perform_request'
        from /usr/local/bundle/gems/elasticsearch-transport-7.17.7/lib/elasticsearch/transport/client.rb:197:in `perform_request'
        from /usr/local/bundle/gems/elasticsearch-7.17.7/lib/elasticsearch.rb:41:in `method_missing'
        from /usr/local/bundle/gems/elasticsearch-api-7.17.7/lib/elasticsearch/api/actions/scroll.rb:57:in `scroll'
        from /home/x/r/lib/register_ingester_dk/clients/dk_client.rb:53:in `scroll'
        from /home/x/r/lib/register_ingester_dk/clients/dk_client.rb:25:in `block in all_records'
        from /home/x/r/lib/register_ingester_dk/apps/ingester.rb:28:in `each'
        from /home/x/r/lib/register_ingester_dk/apps/ingester.rb:28:in `each'
        from /home/x/r/lib/register_ingester_dk/apps/ingester.rb:28:in `each'
        from /home/x/r/lib/register_ingester_dk/apps/ingester.rb:28:in `each_slice'
        from /home/x/r/lib/register_ingester_dk/apps/ingester.rb:28:in `call'
        from /home/x/r/lib/register_ingester_dk/apps/ingester.rb:16:in `bash_call'
        from /home/x/r/bin/ingest-bulk:8:in `<main>'
```

**Comment by tiredpixel** [comment]
It crashed again. I'll give the other processes some time to complete, and then try this for a third time.
